const API_BASE = '/api/v1';

export const URLS = {
    POSTS: {
        BASE: `${API_BASE}/posts`,
        TIMELINE: `${API_BASE}/feed/timeline`,
        EXPLORE: `${API_BASE}/feed/explore`,
        USER_POSTS: (userId) => `${API_BASE}/posts/user/${userId}`,
        BY_ID: (postId) => `${API_BASE}/posts/${postId}`,
        SEARCH: `${API_BASE}/posts/search`,
        VIEW: (postId) => `${API_BASE}/posts/${postId}/view`,
        LIKE: (postId) => `${API_BASE}/posts/${postId}/like`,
        LIKES: (postId) => `${API_BASE}/posts/${postId}/likes`,
        COMMENTS: (postId) => `${API_BASE}/posts/${postId}/comments`,
    },
    COMMENTS: {
        BASE: `${API_BASE}/comments`,
        BY_ID: (commentId) => `${API_BASE}/comments/${commentId}`,
        REPLY: (commentId) => `${API_BASE}/comments/${commentId}/reply`,
        REPLIES: (commentId) => `${API_BASE}/comments/${commentId}/replies`,
        LIKE: (commentId) => `${API_BASE}/comments/${commentId}/like`,
        LIKES: (commentId) => `${API_BASE}/comments/${commentId}/likes`,
    },
    USERS: {
        BASE: `${API_BASE}/users`,
        FOLLOW: (userId) => `${API_BASE}/users/${userId}/follow`,
        FOLLOWERS: (userId) => `${API_BASE}/users/${userId}/followers`,
        FOLLOWING: (userId) => `${API_BASE}/users/${userId}/following`,
        FOLLOW_STATUS: (userId) => `${API_BASE}/users/${userId}/follow-status`,
    },
    PROFILE: {
        BASE: `${API_BASE}/profile`,
        ME: `${API_BASE}/profile/me`,
        BY_ID: (userId) => `${API_BASE}/profile/${userId}`,
        BY_USERNAME: (username) => `${API_BASE}/profile/username/${username}`,
        PICTURE: `${API_BASE}/profile/me/picture`,
        PICTURE_UPLOAD: `${API_BASE}/profile/me/picture/upload`,
        PICTURE_DELETE: `${API_BASE}/profile/me/picture`,
        COVER: `${API_BASE}/profile/me/cover`,
        SEARCH: `${API_BASE}/profile/search`,
    },
    DISCOVERY: {
        BASE: `${API_BASE}/discovery`,
        TRENDING_POSTS: `${API_BASE}/discovery/trending/posts`,
        POPULAR_USERS: `${API_BASE}/discovery/popular/users`,
        STATS: `${API_BASE}/discovery/stats`,
        SUGGESTIONS: `${API_BASE}/discovery/suggestions/users`,
        FOR_YOU: `${API_BASE}/discovery/for-you`,
    },
    MEDIA: {
        BASE: `${API_BASE}/media`,
        UPLOAD: `${API_BASE}/media/upload`,
        UPLOAD_MULTIPLE: `${API_BASE}/media/upload/multiple`,
        BY_ID: (mediaId) => `${API_BASE}/media/${mediaId}`,
        POST_MEDIA: (postId) => `${API_BASE}/media/post/${postId}`,
    },
    HASHTAGS: {
        BASE: `${API_BASE}/hashtags`,
        SEARCH: `${API_BASE}/hashtags/search`,
        TRENDING: `${API_BASE}/hashtags/trending`,
        TOP: `${API_BASE}/hashtags/top`,
        BY_NAME: (tagName) => `${API_BASE}/hashtags/${tagName}`,
        POSTS: (tagName) => `${API_BASE}/hashtags/${tagName}/posts`,
    },
    CHAT: {
        CONVERSATIONS: `${API_BASE}/chat/conversations`,
        CONVERSATION: (conversationId) => `${API_BASE}/chat/conversations/${conversationId}`,
        MESSAGES: (conversationId) => `${API_BASE}/chat/messages/${conversationId}`,
        MESSAGE: (messageId) => `${API_BASE}/chat/messages/${messageId}`,
        MEDIA_UPLOAD: `${API_BASE}/chat/media/upload`,
        SEND_MESSAGE: `${API_BASE}/chat/messages/send`,
    },
    EXPLORE: {
        FOR_YOU: `${API_BASE}/explore/for-you`,
        CATEGORIES: `${API_BASE}/explore/categories`,
        TRENDING: `${API_BASE}/explore/trending`,
        NEWS: `${API_BASE}/explore/news`,
        BREAKING_NEWS: `${API_BASE}/explore/news/breaking`,
        SEARCH: `${API_BASE}/explore/search`,
        TRENDING_POSTS: `${API_BASE}/explore/trending/posts`,
    },
    NOTIFICATIONS: {
        BASE: `${API_BASE}/notifications`,
        BY_TYPE: (type) => `${API_BASE}/notifications/type/${type}`,
        MENTIONS: `${API_BASE}/notifications/mentions`,
        UNREAD_COUNT: `${API_BASE}/notifications/unread-count`,
        UNSEEN_COUNT: `${API_BASE}/notifications/unseen-count`,
        MARK_ALL_READ: `${API_BASE}/notifications/mark-all-read`,
        MARK_ALL_SEEN: `${API_BASE}/notifications/mark-all-seen`,
        MARK_READ: (id) => `${API_BASE}/notifications/${id}/read`,
    }
};

export default URLS;
